### ISSUE TITLE
Errors on functions defined by extensions

### ISSUE THREAD

**Issue by abdurahmanshiine** [wsporto/typesql#26]
Hi there,

I loaded `sqlean/uuid` extension in my libsql server, and when I run this query from the shell it works perfectly fine:
```sql
INSERT INTO users (id, name) VALUES ( (SELECT uuid4()), 'Shiine');
```
But when I create `insert-user.sql` file containing the same exact query, the compiler fails to compile and throws this error:
```bash
ERROR:  no such function: uuid4
at  src/data/repos/custom-queries/users/insert-user.sql
```

**Comment by wsporto** [comment]
Thanks for reporting.  Loading an extension is not currently supported by TypeSQL. I started exploring the following solution:

1. Add `loadExtension` and `extensionCatalog` options on the `typesql.json`:

```
{
    "databaseUri": "./mydb.db",
    "sqlDir": "./src/sql",
    "client": "libsql",
    "includeCrudTables": [],
    "loadExtensions": ["./ext/uuid.dll"],
    "extensionCatalog": {
        "sqlean/uuid": true
    }
}
```

The `extensionCatalog` option will be used to define the parameters and return types of the functions. TypeSQL will generate the functions and parameters type as `any` if they are not informed.  

Since the `sqlean/uuid` extensions are widely used, they will be already pre-configured, needing only to add the value "true". For others not pre-configured, it will be necessary to include the return and parameter types for each function (or TypeSQL will infer their types as 'any').

This configuration option (experimental) was added in v0.10.7 with support for the uuid4() and uuid7() functions. Other functions will be added in future releases.

Please, check if that fixed the issue.

**Comment by abdurahmanshiine** [comment]
Hey @wsporto 

I tried the solution you proposed, but I'm still getting the same error. This is my `typesql.json` file:
```json
{
    "databaseUri": "./local.db",
    "sqlDir": "./src/data/repos/custom-queries/",
    "client": "libsql",
    "includeCrudTables": [],
    "extensionCatalog": {
      "sqlean/uuid": true
    }
}
```
Am I getting something wrong?

P.S.
I'm using `Bun 1.1.18` & `typesql-cli 0.10.7`

**Comment by wsporto** [comment]
Hi, @abdurahmanshiine 

You also need to specify the path to the extensions being used in the loadExtensions property (*.dll for Windows, *.so for Linux, *.dylib for macOS). Ex.:

```js
{
    "databaseUri": "./local.db",
    "sqlDir": "./src/data/repos/custom-queries/",
    "client": "libsql",
    "includeCrudTables": [],
    "loadExtensions": ["./libs/uuid.so"],
    "extensionCatalog": {
      "sqlean/uuid": true
    }
}
```
I plan to use a TypeScript file for the TypeSQL configuration (typesql.config.ts). This will allow the same configuration to be used for both TypeSQL and the database client.

**Comment by abdurahmanshiine** [comment]
Yes, this works great. Thanks a lot.

And thanks more for such a great library, I truly find it a joy to use.
