### ISSUE TITLE
Multiple queries in same file

### ISSUE THREAD

**Issue by zareith** [wsporto/typesql#28]
Thanks for creating this library. Looks like a great concept. 

Curious if you'd be interested in supporting multiple queries in same file. This could be similar to what pgtyped does (https://pgtyped.dev/docs/sql-file). 

The primary motivation is that in my application I'd have a lot of small/medium sql queries and creating a file for each of them requires a lot of jumping around.

**Comment by wsporto** [comment]
Thank you for the suggestion, @zareith!  

The decision to maintain one file for each query was primarily made to facilitate navigation between the generated function and the associated SQL (clicking or using the IDE's "Go to File" feature).

While it might seem more convenient to have several queries in one file, this could make it harder to find specific queries, especially as the number of queries grows. After navigating to a file you would still need to search within it to find the desired query. 

Instead of having multiple queries into one file you could organize the SQL files in sub-folders, for example:

```sh
/users
   /delete-users.sql
   /inactivate-user.sql
   /select-users.sql
   /update-users.sql
/posts
   /select-posts.sql
   /insert-post.sql
```
For the basic CRUD queries you can use the [automatic CRUD generation](https://typesql.pages.dev/guides/crud/) feature.
