### ISSUE TITLE
Undefined is passed as default argument

### ISSUE THREAD

**Issue by lthi747** [wsporto/typesql#36]
As per example of https://typesql.pages.dev/guides/conditional-filters/

I am getting error like

```
[ERROR] [router] TypeError: undefined cannot be passed as argument to the database
```

Using next query

```
SELECT * FROM taxonomy
WHERE
	(:id IS NOT NULL AND id = :id)
	OR (:parent_taxonomy_id IS NOT NULL AND parent_taxonomy_id = :parent_taxonomy_id)
```

I am trying to call like

`await getTestTax(db, { id: 258 })`

Also the TS is complaining

```
Argument of type '{ id: number; }' is not assignable to parameter of type 'TestParams'.
  Property 'parent_taxonomy_id' is missing in type '{ id: number; }' but required in type 'TestParams'.ts(2345)
```

May be by default should be passed null as default value for the parameters, or if used in IN/BETWEEN then empty array

**Comment by wsporto** [comment]
This is an interesting use case. For your query, TypeSQL currently generates the type as:
```ts
type GetTestTaxParams = { 
   id: number | null; 
   parent_id: number | null 
}
```
In earlier versions, it was generated as (with optional parameters):
```ts
type GetTestTaxParams = { 
   id?: number | null; 
   parent_id?: number | null 
}
```
This made the parameters optional, which often led to users forgetting to pass them. The current version now requires all parameters to be explicitly defined.

For your query, you should run getTestTax with:
```ts
await getTestTax(db, { id: 128, parent_id: null });
```
This change is important because, with optional parameters, adding new optional parameters to the SQL would allow the code to compile without requiring any changes, potentially causing issues.

Alternatively, for more dynamic queries, you can use the `@dynamicQuery` annotation. With `@dynamicQuery`, your query would look like this:

```sql
-- @dynamicQuery
SELECT * FROM taxonomy
```
And you can execute the query with:

```ts
await getTestTax(db, { 
   where: [ 
      ['id', '=', 128] 
   ] 
});
```
